name: 'action-use-template'
author: 'hocgin'
description: '在使用`use template repository`时候，替换模版仓库里面的变量'
inputs:
  left_delim:
    required: true
    default: '<<['
    description: '变量左匹配符'
  right_delim:
    required: true
    default: ']>>'
    description: '变量右匹配符'
  path:
    required: true
    default: '**/*'
    description: '作用文件或目录'
  exclude:
    description: '忽略文件或目录(,分隔)'
  exclude_file:
    description: '忽略文件或目录的变量路径'
  overflow_readme_file:
    description: '覆盖 README.md 的文件路径'
  env_file:
    description: '替换的变量文件路径'
  env:
    description: '替换的变量列表: key=value,key2=value2'
  debug:
    default: 'false'
    description: '调试'
#outputs:
runs:
  using: node12
  main: dist/index.js
